version: '3.8'

services:
  backend:
    # build: ./backend
    image: ${DOCKER_USERNAME}/task-manager-backend:latest
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmanager
    depends_on:
      - db

  frontend:
    # build: ./frontend
    image: ${DOCKER_USERNAME}/task-manager-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: