name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: taskmanager_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Debug directory structure
      run: |
        pwd
        ls -la
        echo "Backend directory:"
        ls -la backend/
        echo "Frontend directory:"
        ls -la frontend/
        echo "Checking for package-lock.json files:"
        find . -name "package-lock.json"

    - name: Set up Node.js for Backend
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          backend/package.json

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm install
        npm ci
        npm list --depth=0

    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          frontend/package.json

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm ci
        npm list --depth=0

    - name: Verify backend test setup
      working-directory: ./backend
      run: |
        echo "Checking test setup file:"
        ls -la src/tests/setup.ts
        echo "Checking Jest config:"
        cat config/jest.config.js

    - name: Run backend tests
      working-directory: ./backend
      run: |
        npm run test
        npm run test:coverage
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/taskmanager_test

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm run test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/task-manager-backend:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/task-manager-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          # Ensure Docker is installed and running
          if ! command -v docker &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
          fi
          
          # Install docker-compose if not present
          if ! command -v docker-compose &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin
            sudo ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
          fi
          
          # Create application directory
          sudo mkdir -p /opt/task-manager
          sudo chown $USER:$USER /opt/task-manager
          
          # Navigate to application directory
          cd /opt/task-manager
          
          # Create docker-compose.yml
          sudo tee docker-compose.yml << 'EOL'
          services:
            backend:
              image: ${{ secrets.DOCKER_USERNAME }}/task-manager-backend:latest
              ports:
                - "3001:3000"
              environment:
                - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskmanager
              depends_on:
                - db
            frontend:
              image: ${{ secrets.DOCKER_USERNAME }}/task-manager-frontend:latest
              ports:
                - "80:80"
              depends_on:
                - backend
            db:
              image: postgres:15-alpine
              environment:
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres
                - POSTGRES_DB=taskmanager
              volumes:
                - postgres_data:/var/lib/postgresql/data
          volumes:
            postgres_data:
          EOL
          
          # Set proper permissions
          sudo chown $USER:$USER docker-compose.yml
          
          # Pull latest images and start containers using sudo
          sudo docker-compose pull
          sudo docker-compose up -d
