name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci
      - name: Run backend unit tests
        working-directory: ./backend
        run: npm test
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run frontend unit tests
        working-directory: ./frontend
        run: npm test

  build-and-push:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fullstack-app-backend:latest
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fullstack-app-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.AWS_HOST }}" ]; then
            echo "::error::AWS_HOST secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_KEY }}" ]; then
            echo "::error::AWS_KEY secret is not set"
            exit 1
          fi
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -v ubuntu@${{ secrets.AWS_HOST }} 'echo "SSH connection successful"'
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          port: 22
          debug: true
          script: |
            cd /home/ubuntu/fullstack-app
            # Set environment variables
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            # Pull and start services
            docker-compose pull
            docker-compose up -d
            # Wait for services to be ready
            sleep 30
            # Verify services are running
            docker-compose ps
            # Check if ports are listening
            netstat -tulpn | grep LISTEN
            # Check docker logs
            docker-compose logs

  integration-tests:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: ./tests
        run: npm install --legacy-peer-deps
      - name: Run integration tests
        working-directory: ./tests
        env:
          APP_URL: http://${{ secrets.AWS_HOST }}
          BACKEND_PORT: 4000
        run: npx codeceptjs run --steps --verbose 